version: '3'
services:
  seed:
    build: db-seed
    volumes:
      - ./db-seed:/app
      - /app/node_modules
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    depends_on:
      - seed
    volumes:
      - ./scripts:/scripts
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: computervision
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpwd
